### ISSUE TITLE
Add coreset k-medoid algorithms

### ISSUE THREAD

**Issue by jianshu93** [kno10/rust-kmedoids#4]
Dear rust-kmedoids team, 

It seems several recently publications on coreset can be applied in the k-medoid case for approximate clustering. Check the newly developed coreset crate here: https://github.com/jean-pierreBoth/coreset

It seems only metric space is supported by coreset.

Thank you,

Jianshu

**Comment by kno10** [comment]
In my experience, coreset approaches are mostly of theoretical interest because of the constant factors.
For many practical applications, you can either afford to just run the full optimization, or you can just sample uniformly  and use the sample solution.
BanditPAM is another recent proposal (#3, NeurIPS 2020, NeurIPS 2023) where in my experience the theoretical results to do not transfer to practical benefits.
For both you can find implementations online - try them out, and let me know if they work well for you.

Both methods are currently out of scope for this package because they need distance functions, and this package currently operates only on precomputed distance matrices, and we do not include a single distance function so far.
